tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      export AWS_ACCESS_KEY=$(gp env AWS_Access_Key)
      export AWS_SECRET_KEY=$(gp env AWS_Secret_Key)
      


      
vscode:
  extensions:
    - 42Crunch.vscode-openapi