[deploy]
bucket = 'cfn-artifacts-bckt'
region = 'ap-south-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:ap-south-1:651746472793:certificate/84c13a7f-c22a-4c2a-8659-ede321c72f78'
NetworkingStack = 'CrdNet'