[deploy]
bucket = 'cfn-artifacts-bckt'
region = 'ap-south-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
BuildSpec = 'backend-flask/buildspec.yml'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'rath23/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipeline-cruddur-artifacts-maq"